version: 1.6.3.{build}

os: Visual Studio 2017

build_script:
- ps: dotnet restore
- ps: dotnet pack src\CoreTweetSupplement\CoreTweetSupplement.csproj -c Release

test_script:
- ps: dotnet test test\CoreTweetSupplement.Tests\CoreTweetSupplement.Tests.csproj

artifacts:
- path: src\CoreTweetSupplement\bin\Release\*.nupkg
